import type { LegacyDataset, LegacyFriend } from '@/types';

export const INITIAL_FRIENDS: Record<string, LegacyFriend> = {
  shawon: {
    id: 'shawon',
    name: 'Shawon',
    role: 'AI / Deep Learning Applicant',
    avatar: 'S',
    color: '#10b981', // Emerald
    glowColor: 'rgba(16, 185, 129, 0.35)',
    accentBg: 'rgba(16, 185, 129, 0.12)',
  },
  imran: {
    id: 'imran',
    name: 'Imran',
    role: 'Systems & NLP Applicant',
    avatar: 'I',
    color: '#38bdf8', // Sky Blue
    glowColor: 'rgba(56, 189, 248, 0.35)',
    accentBg: 'rgba(56, 189, 248, 0.12)',
  },
  mahmud: {
    id: 'mahmud',
    name: 'Mahmud',
    role: 'Robotics & Vision Applicant',
    avatar: 'M',
    color: '#f59e0b', // Amber
    glowColor: 'rgba(245, 158, 11, 0.35)',
    accentBg: 'rgba(245, 158, 11, 0.12)',
  },
};

export const INITIAL_DATASET: LegacyDataset = {
  version: '1.0.0',
  friends: INITIAL_FRIENDS,
  universities: [
    {
      id: 'uni-cmu',
      name: 'Carnegie Mellon University',
      country: 'United States',
      city: 'Pittsburgh, PA',
      ranking: 1,
      portalUrl: 'https://www.cs.cmu.edu/academics/admissions',
      websiteUrl: 'https://www.cmu.edu',
      notes: 'Premier institution for CS and AI. Application deadline usually Dec 12.',
      createdAt: '2026-09-01T10:00:00.000Z',
      departments: [
        {
          id: 'dept-cmu-csd',
          universityId: 'uni-cmu',
          name: 'Computer Science Department (CSD)',
          degreeLevel: 'PhD',
          websiteUrl: 'https://csd.cmu.edu',
          deadlines: {
            fall: '2026-12-10',
            spring: 'Not Offered',
          },
          requirements: {
            gre: 'Optional for 2026-2027',
            toeflOrIelts: 'TOEFL 100+ (25+ subscores) or IELTS 7.5+',
            feeWaiverAvailable: true,
            feeWaiverNotes: 'Apply via SCS Fee Waiver program before Nov 15.',
          },
          createdAt: '2026-09-01T10:05:00.000Z',
          professors: [
            {
              id: 'prof-cmu-ruslan',
              departmentId: 'dept-cmu-csd',
              name: 'Prof. Ruslan Salakhutdinov',
              title: 'Professor of Computer Science',
              email: 'rsalakhu@cs.cmu.edu',
              websiteUrl: 'https://www.cs.cmu.edu/~rsalakhu/',
              scholarUrl: 'https://scholar.google.com/citations?user=dOqFA2AAAAAJ',
              researchAreas: ['Deep Learning', 'Generative AI', 'Multimodal LLMs', 'Representation Learning'],
              acceptingStudents: 'yes',
              notes: 'Looking for students with strong math background and top publications.',
              createdAt: '2026-09-01T10:10:00.000Z',
              outreach: {
                shawon: {
                  friendId: 'shawon',
                  status: 'positive',
                  dateEmailed: '2026-09-08',
                  responseDate: '2026-09-10',
                  notes: 'Prof. Ruslan replied encouraging formal application and asked to review his recent ICLR 2026 preprint on reasoning models.',
                  emailSubject: 'Prospective PhD Student (Fall 2027) - Inquiring on Generative Reasoning Lab Openings',
                  lastUpdated: '2026-09-10T14:30:00.000Z',
                },
                imran: {
                  friendId: 'imran',
                  status: 'not_contacted',
                  lastUpdated: '2026-09-01T10:10:00.000Z',
                },
                mahmud: {
                  friendId: 'mahmud',
                  status: 'drafting',
                  notes: 'Preparing email highlighting past work on diffusion representations.',
                  lastUpdated: '2026-09-18T16:00:00.000Z',
                },
              },
            },
            {
              id: 'prof-cmu-neubig',
              departmentId: 'dept-cmu-csd',
              name: 'Prof. Graham Neubig',
              title: 'Associate Professor, LTI & CSD',
              email: 'gneubig@cs.cmu.edu',
              websiteUrl: 'https://www.phontron.com/',
              scholarUrl: 'https://scholar.google.com/citations?user=k9Gz3vAAAAAJ',
              researchAreas: ['Natural Language Processing', 'Code Generation', 'Agentic LLMs'],
              acceptingStudents: 'yes',
              notes: 'Very active lab. Check lab website for explicit instructions before cold emailing.',
              createdAt: '2026-09-02T11:00:00.000Z',
              outreach: {
                shawon: {
                  friendId: 'shawon',
                  status: 'not_contacted',
                  lastUpdated: '2026-09-02T11:00:00.000Z',
                },
                imran: {
                  friendId: 'imran',
                  status: 'emailed',
                  dateEmailed: '2026-09-15',
                  followUpDate: '2026-09-23',
                  emailSubject: 'Prospective PhD Applicant - Code Intelligence & Automated Debugging Research',
                  notes: 'Mentioned my benchmark paper on LLM execution traces. Follow up if no reply in 8 days.',
                  lastUpdated: '2026-09-15T09:12:00.000Z',
                },
                mahmud: {
                  friendId: 'mahmud',
                  status: 'not_contacted',
                  lastUpdated: '2026-09-02T11:00:00.000Z',
                },
              },
            },
          ],
        },
        {
          id: 'dept-cmu-ri',
          universityId: 'uni-cmu',
          name: 'The Robotics Institute (RI)',
          degreeLevel: 'PhD & MS',
          websiteUrl: 'https://www.ri.cmu.edu',
          deadlines: {
            fall: '2026-12-12',
            spring: 'Not Offered',
          },
          requirements: {
            gre: 'Not required',
            toeflOrIelts: 'TOEFL 100+ or IELTS 7.5+',
            feeWaiverAvailable: true,
          },
          createdAt: '2026-09-03T12:00:00.000Z',
          professors: [
            {
              id: 'prof-cmu-sycara',
              departmentId: 'dept-cmu-ri',
              name: 'Prof. Katia Sycara',
              title: 'Research Professor, Robotics Institute',
              email: 'sycara@cs.cmu.edu',
              websiteUrl: 'https://www.ri.cmu.edu/ri-faculty/katia-sycara/',
              scholarUrl: 'https://scholar.google.com/citations?user=eX7L8GAAAAAJ',
              researchAreas: ['Multi-Agent Systems', 'Human-Robot Teaming', 'Autonomous Vehicles'],
              acceptingStudents: 'yes',
              notes: 'Pioneer in multi-agent reinforcement learning.',
              createdAt: '2026-09-03T12:15:00.000Z',
              outreach: {
                shawon: {
                  friendId: 'shawon',
                  status: 'not_contacted',
                  lastUpdated: '2026-09-03T12:15:00.000Z',
                },
                imran: {
                  friendId: 'imran',
                  status: 'not_contacted',
                  lastUpdated: '2026-09-03T12:15:00.000Z',
                },
                mahmud: {
                  friendId: 'mahmud',
                  status: 'interview',
                  dateEmailed: '2026-09-05',
                  responseDate: '2026-09-12',
                  notes: 'Quick Zoom chat scheduled for upcoming Tuesday to discuss swarm coordination simulations.',
                  emailSubject: 'Inquiry on Multi-Agent Robotics PhD Vacancies',
                  lastUpdated: '2026-09-12T18:00:00.000Z',
                },
              },
            },
          ],
        },
      ],
    },
    {
      id: 'uni-uw',
      name: 'University of Washington',
      country: 'United States',
      city: 'Seattle, WA',
      ranking: 5,
      portalUrl: 'https://www.cs.washington.edu/academics/phd/admissions',
      websiteUrl: 'https://www.washington.edu',
      notes: 'World-class systems and AI research. Great ties with Microsoft Research, Amazon, and AI2.',
      createdAt: '2026-09-04T14:00:00.000Z',
      departments: [
        {
          id: 'dept-uw-cse',
          universityId: 'uni-uw',
          name: 'Paul G. Allen School of Computer Science & Engineering',
          degreeLevel: 'PhD',
          websiteUrl: 'https://www.cs.washington.edu',
          deadlines: {
            fall: '2026-12-15',
          },
          requirements: {
            gre: 'Not accepted / Blind',
            toeflOrIelts: 'Duolingo 125+, TOEFL 100, or IELTS 7.0',
            feeWaiverAvailable: true,
            feeWaiverNotes: 'Direct fee waiver request on Allen School site by Dec 1.',
          },
          createdAt: '2026-09-04T14:10:00.000Z',
          professors: [
            {
              id: 'prof-uw-farhadi',
              departmentId: 'dept-uw-cse',
              name: 'Prof. Ali Farhadi',
              title: 'Professor & CEO at AI2',
              email: 'ali@cs.washington.edu',
              websiteUrl: 'https://homes.cs.washington.edu/~ali/',
              scholarUrl: 'https://scholar.google.com/citations?user=X6_5qfMAAAAJ',
              researchAreas: ['Computer Vision', 'Embodied AI', 'Open Foundation Models', 'YOLO / Prior'],
              acceptingStudents: 'maybe',
              notes: 'Co-leads Prior lab at AI2 and UW.',
              createdAt: '2026-09-04T14:20:00.000Z',
              outreach: {
                shawon: {
                  friendId: 'shawon',
                  status: 'drafting',
                  notes: 'Drafting email around OLMo architecture and embodied navigation.',
                  lastUpdated: '2026-09-17T11:00:00.000Z',
                },
                imran: {
                  friendId: 'imran',
                  status: 'not_contacted',
                  lastUpdated: '2026-09-04T14:20:00.000Z',
                },
                mahmud: {
                  friendId: 'mahmud',
                  status: 'emailed',
                  dateEmailed: '2026-09-14',
                  followUpDate: '2026-09-22',
                  emailSubject: 'Prospective PhD Student - Embodied Vision & Manipulation',
                  notes: 'Mentioned my work with simulation in RoboThor.',
                  lastUpdated: '2026-09-14T15:20:00.000Z',
                },
              },
            },
          ],
        },
      ],
    },
    {
      id: 'uni-tum',
      name: 'Technical University of Munich (TUM)',
      country: 'Germany',
      city: 'Munich',
      ranking: 28,
      portalUrl: 'https://campus.tum.de',
      websiteUrl: 'https://www.tum.de',
      notes: 'No tuition fees! Low administrative semester contribution. Excellent robotics and vision.',
      createdAt: '2026-09-05T09:00:00.000Z',
      departments: [
        {
          id: 'dept-tum-cit',
          universityId: 'uni-tum',
          name: 'School of Computation, Information and Technology (CIT)',
          degreeLevel: 'PhD & MS',
          websiteUrl: 'https://www.cit.tum.de',
          deadlines: {
            fall: '2027-05-31',
            spring: '2026-11-30',
          },
          requirements: {
            gre: 'Recommended for non-EU applicants',
            toeflOrIelts: 'IELTS 6.5+ or TOEFL 88+',
            feeWaiverAvailable: false,
            feeWaiverNotes: 'Tuition is free or nominal for EU/non-EU research grants.',
          },
          createdAt: '2026-09-05T09:10:00.000Z',
          professors: [
            {
              id: 'prof-tum-cremers',
              departmentId: 'dept-tum-cit',
              name: 'Prof. Dr. Daniel Cremers',
              title: 'Chair for Computer Vision & Artificial Intelligence',
              email: 'cremers@tum.de',
              websiteUrl: 'https://cvg.cit.tum.de/members/cremers',
              scholarUrl: 'https://scholar.google.com/citations?user=nZgJv48AAAAJ',
              researchAreas: ['3D Reconstruction', 'Visual SLAM', 'Neural Radiance Fields', 'Autonomous Systems'],
              acceptingStudents: 'yes',
              notes: 'Runs the renowned Computer Vision Group (CVG) at TUM.',
              createdAt: '2026-09-05T09:15:00.000Z',
              outreach: {
                shawon: {
                  friendId: 'shawon',
                  status: 'not_contacted',
                  lastUpdated: '2026-09-05T09:15:00.000Z',
                },
                imran: {
                  friendId: 'imran',
                  status: 'not_contacted',
                  lastUpdated: '2026-09-05T09:15:00.000Z',
                },
                mahmud: {
                  friendId: 'mahmud',
                  status: 'positive',
                  dateEmailed: '2026-09-06',
                  responseDate: '2026-09-11',
                  notes: 'Assistant coordinator replied that a HiWi/PhD position in 3D Gaussian Splatting is opening in January.',
                  emailSubject: 'PhD Candidate Application - 3D Neural Scene Representation',
                  lastUpdated: '2026-09-11T13:45:00.000Z',
                },
              },
            },
          ],
        },
      ],
    },
  ],
  activityLogs: [
    {
      id: 'log-1',
      timestamp: '2026-09-12T18:00:00.000Z',
      friendId: 'mahmud',
      action: 'updated_outreach',
      description: 'Mahmud scheduled an interview with Prof. Katia Sycara (CMU RI)',
      metadata: {
        professorName: 'Prof. Katia Sycara',
        newStatus: 'interview',
      },
    },
    {
      id: 'log-2',
      timestamp: '2026-09-11T13:45:00.000Z',
      friendId: 'mahmud',
      action: 'updated_outreach',
      description: 'Mahmud received a Positive Reply from Prof. Dr. Daniel Cremers (TUM)',
      metadata: {
        professorName: 'Prof. Dr. Daniel Cremers',
        newStatus: 'positive',
      },
    },
    {
      id: 'log-3',
      timestamp: '2026-09-10T14:30:00.000Z',
      friendId: 'shawon',
      action: 'updated_outreach',
      description: 'Shawon received a Positive Reply from Prof. Ruslan Salakhutdinov (CMU CSD)',
      metadata: {
        professorName: 'Prof. Ruslan Salakhutdinov',
        newStatus: 'positive',
      },
    },
    {
      id: 'log-4',
      timestamp: '2026-09-15T09:12:00.000Z',
      friendId: 'imran',
      action: 'updated_outreach',
      description: 'Imran emailed Prof. Graham Neubig (CMU LTI & CSD)',
      metadata: {
        professorName: 'Prof. Graham Neubig',
        newStatus: 'emailed',
      },
    },
  ],
};
